ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG JAVA

# https://docs.bell-sw.com/liberica-jdk/latest/general/install-guide/#linux
RUN <<EOT
set -e
export DEBIAN_FRONTEND="noninteractive"
if [ -n "$JAVA" ]; then
  apt-get update
  apt-get install --no-install-recommends -y gnupg ca-certificates curl
  curl -so- https://download.bell-sw.com/pki/GPG-KEY-bellsoft | gpg --dearmor -o /etc/apt/trusted.gpg.d/bellsoft.gpg
  echo "deb https://apt.bell-sw.com/ stable main" | tee /etc/apt/sources.list.d/bellsoft.list
  apt-get update
  apt-get install --no-install-recommends -y "bellsoft-java${JAVA}"
  rm -rf /var/lib/apt/lists/*
else
  exit 1
fi
EOT
