ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG JAVA=17

# https://adoptium.net/installation/linux/
RUN <<EOT
set -eux
export DEBIAN_FRONTEND="noninteractive"

apt-get update
apt-get install -y gnupg ca-certificates curl
curl -so- https://packages.adoptium.net/artifactory/api/gpg/key/public | tee /etc/apt/keyrings/adoptium.asc
echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
apt-get update

# The temurin deb source is currently very unstable, using apt-get to install might randomly fail and retry does not work
# https://github.com/adoptium/adoptium-support/issues/554
# https://github.com/adoptium/installer/issues/766
url=$(apt-get install --print-uris -qq temurin-${JAVA}-jdk | grep "temurin-${JAVA}-jdk" | head -n 1 | cut -d "'" -f2)
echo "deb url: $url"
set +e
for attempt in $(seq 1 5); do
  if curl "$url" -o /tmp/temurin.deb; then
    break
  fi
  echo "Download attempt #$attempt failed. Waiting 30 seconds..."
  sleep 30
  update-ca-certificates
done
dpkg -i /tmp/temurin.deb
set -e

apt-get -y -f install
java -version

rm -f /tmp/temurin.deb
rm -rf /var/lib/apt/lists/*
EOT
