ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG JAVA=17

# https://docs.bell-sw.com/liberica-jdk/latest/general/install-guide/#linux
RUN <<EOT
set -eux
export DEBIAN_FRONTEND="noninteractive"

apt-get update
apt-get install -y gnupg ca-certificates curl
curl -so- https://download.bell-sw.com/pki/GPG-KEY-bellsoft | gpg --dearmor -o /etc/apt/trusted.gpg.d/bellsoft.gpg
echo "deb https://apt.bell-sw.com/ stable main" | tee /etc/apt/sources.list.d/bellsoft.list
apt-get update
apt-get install -y "bellsoft-java${JAVA}"
java -version
rm -rf /var/lib/apt/lists/*
EOT
