ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG JAVA=17

# https://docs.azul.com/core/install/debian#install-from-azul-apt-repository
RUN <<EOT
set -eux
export DEBIAN_FRONTEND="noninteractive"

apt-get update
apt-get install -y gnupg ca-certificates curl
curl -so- https://repos.azul.com/azul-repo.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/azul.gpg
echo "deb https://repos.azul.com/zulu/deb stable main" | tee /etc/apt/sources.list.d/zulu.list
apt-get update
apt-get install -y "zulu${JAVA}-jdk"

java -version
javac -version
rm -rf /var/lib/apt/lists/*
EOT
