ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG JAVA=17

# https://docs.aws.amazon.com/corretto/latest/corretto-17-ug/generic-linux-install.html
RUN <<EOT
set -eux
export DEBIAN_FRONTEND="noninteractive"

apt-get update
apt-get install -y gnupg ca-certificates curl
curl -so- https://apt.corretto.aws/corretto.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/corretto.gpg
echo "deb https://apt.corretto.aws stable main" | tee /etc/apt/sources.list.d/corretto.list

apt-get update
if [ "$JAVA" = "8" ]; then
  JAVA="1.8.0"
fi
apt-get install -y "java-${JAVA}-amazon-corretto-jdk"

java -version
javac -version
rm -rf /var/lib/apt/lists/*
EOT
