ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY requirements_extra.txt /tmp/

RUN <<EOT
set -eux
# disable the pip config temporary to install packages to the global storage
export PIP_CONFIG_FILE=/dev/null

pip freeze | grep mcdreforged >> /tmp/requirements_extra.txt
pip3 install -r /tmp/requirements_extra.txt

rm -f /tmp/requirements_extra.txt
pip3 cache purge && rm -rf ~/.cache/
EOT
